language: android
script: "./gradlew assembleDebug"

jdk:
  - oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-25.0.0
    - build-tools-27.0.0
    # The SDK version used to compile your project
    - android-25
    - android-27
    - extra-android-m2repository
    - extra-android-support
    # Additional components
    #- extra-android-m2repository
  licenses:
    - android-sdk-license-.+
